language: ruby
rvm:
  - 1.9.3
# 実行するスクリプト
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec

# # Herokuへのデプロイの設定 ##################################################
# # 環境変数に暗号化したHerokuのAPIキーを設定
# env:
#   global:
#     - secure: EFKwohfRjl8FY8Jvt4awJAQxp2p8YmPhXuUxxyBW73JPNnKZbYtSo0vR9vxV\nM+2ryLWkim86ySh58pJGpCvyLp/VLgUkqcVRlEK79Gf1EvkfU3bz7oekB4vc\n7Wq/I/IePbQuaPPvfuxZ+k9A6sIog1gWAAVtubOWAtRybgXSqFk=

# # ビルドが成功した後に実行するスクリプト
# after_success:
#   # toolbeltのダウンロード
#   - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
#   # herokuのリポジトリを指定
#   - git remote add heroku git@studentsmanager.git
#   # <~/.ssh/config>に設定を追加
#   - echo "Host heroku.com" >> ~/.ssh/config
#   - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
#   - echo "   CheckHostIP no" >> ~/.ssh/config
#   - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
#   # herokuへデプロイして色々やる
#   - heroku keys:clear
#   - yes | heroku keys:add
#   - yes | git push heroku master
#   - heroku run rake db:migrate
#   - heroku restart