language: ruby
rvm:
  - 1.9.3
notifications:
  email: false
bundler_args: --deployment
script:
  - bundle exec rake db:migrate
  - bundle exec rake spec

env:
  global:
    secure: ! '1f9orHZkf0fP1N/HiN9UzW6h1xPx/SzBS2X2zsO8Yf63381hH+lW2z4txNmE
      X5Ouyw8BZ5ufJpp86GPitYIRxaykafDdpGjoJKNEwRKJM1yq9dhBCuEr4IjR
      XNg0venKJkldhfdAVH8VnVbxopzoQaRBoCD75JLx8aOJ045q5D8='

after_success:
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; 
  - then
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:studentsmanager2.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push heroku master
#  - heroku pg:reset DATABASE --confirm studentsmanager
  - heroku run rake db:migrate
#  - heroku run rake db:seed
  - heroku restart
  
  - elif [[ "$TRAVIS_BRANCH" = "release" ]]; then exit 0; fi
  - then
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  - git remote add heroku git@heroku.com:studentsmanager.git
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  - heroku keys:clear
  - yes | heroku keys:add
  - yes | git push -f heroku HEAD:master
  - heroku run rake db:migrate
  - heroku restart  
  
  - else
  - then exit 0; 
  - fi
